### PR TITLE
In specs separate data setup, action, and expectations by whitespace

### PR DESCRIPTION
**Pull request by coreycondardo**
Why?

Specs contain three distinct parts:
  1) The data setup
  2) The execution of a thing
  3) The expectation.

When reasoning about a test, you are usually thinking about how you setup data, what you are executing, or what you are expecting. Because they are three distinct building blocks of a spec and are usually reasoned about separately, I prefer they are visually separated.

In practice, this makes finding the distinction between the 3 blocks you want to change / understand easier.

The only exception I can see is when you have 1 line per each block. Whitespace can be cumbersome in that case, and I'd be okay tweaking the guideline to account for that, if it's preferred.

### CODE REVIEW

**Comment by glanotte** [comment]
I will say I am ambivalent toward this, I think it gets tricky when you start talking about mocks where the expectation can precede the action.

**Comment by coreycondardo** [comment]
Agreed. You could add that tho. My point is, specs are made up of distinct blocks. I'm advocating we break those up unless they are the most trivial (3 lines).

**Comment by chardoublestar** [comment]
There are expectations that have to be setup before the execution. I recently saw some in `spec/lib/spamalot/black_list_spec.rb`

**Comment by dmccraw** [comment]
I like having it broken into three parts as well but I try to follow whatever pattern is in the file at the time. My question is if I write it in this format from now on will people reject the pr?

**Comment by coreycondardo** [comment]
@chardoublestar thanks for pointing that out. Here are two examples from that file, both worth considering.

```
  it "sends a notification when blocking a user" do
      user_id = 1
      expect(Spamalot::Slack).to receive(:notify_hellban).with(user_id)
      Spamalot::Blacklist.new(user_id).hellban
    end
```
☝️ This one is reasonable to parse. Order is different, and no whitespace is present.
```
    it "blocks a user after they pass the threshhold" do
      user_id = 1
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 1
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 2
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 3
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 4
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 5
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 6
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 7
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_hellban).with(user_id)
      black_list = Spamalot::Blacklist.new(user_id)
      8.times { black_list.increment }
      expect(black_list).to be_hellbanned
      expect(black_list.threat_level).to be(900)
    end
```
☝️ This one is a bit of a wall of text. With this PR accepted, it'd end up looking like this:
```
    it "blocks a user after they pass the threshhold" do
      user_id = 1
      black_list = Spamalot::Blacklist.new(user_id)
      
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 1
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 2
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 3
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 4
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 5
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 6
      ).ordered
      expect(Spamalot::Slack).to receive(:notify_increment).with(
        user_id, :current_level => 7
      ).ordered      
      expect(Spamalot::Slack).to receive(:notify_hellban).with(user_id)
      
      8.times { black_list.increment }
      
      expect(black_list).to be_hellbanned
      expect(black_list.threat_level).to be(900)
    end
```
☝️ That certainly pushes the boundaries of this guideline! :). 

You'll notice I moved the test data from below the pre-execution expectations up to the top (so all data creating is together). Personally that's easier to reason about, and the end-goal of this PR.

**Comment by knappe** [comment]
I really enjoy the separation of items.  I try and write not just my tests this way, but also my code.  It *feels* a lot cleaner to me.

**Comment by chardoublestar** [comment]
I generally like this idea too. The additional "separation" I might do within a spec is when setting up multiple items-of-the-same-type that might be needed. I find it hard to track which instance is needed for what purpose, so I try to clump together the setup of relational data needed for each item with some obvious naming.

**Comment by dmccraw** [comment]
I like the separation as well. It makes it easy to determine setup, actions and expectations.

**Pull request merged**
