### PR TITLE
Add some notes about prefixing git commites and PRs and about rebase/squash.

### PR DESCRIPTION
**Pull request by wbarn**
Not sure how I feel about squashing all PRs. Curious what others thoughts are.

### CODE REVIEW

**Comment by knappe** [comment]
Personally, I don't find squashing useful.  I like the history of a PR to be articulated -- it shows how people work and allows you to see that.  Squashing was useful when reverts were hard, but GH allows us to do this easily now.

I will request that people tidy up commit messages and drop `WIP` commits, but I don't think squashing is necessary (since the former should fix the latter).

**Comment by coreycondardo** [comment]
I'd be in favor of something like "ensure all commit messages provide useful context" or something similarly open-ended.

I don't think squashing 100% of the time is a requirement, i just prefer:
```
added ability to xxxxx
corrected xxx endpoint with xxxx
```
over
```
fixed
really fixed
okay this time
fix nits
added ability to xxxxx
oops lolz
corrected xxx endpoint with xxxx
```

**Comment by dmccraw** [comment]
I usually squash down to a few commits with each commit following this format:
http://chris.beams.io/posts/git-commit/

**Comment by wbarn** [comment]
Updated the text a bit. Additional thoughts?

**Comment by wbarn** [comment]
@semmons99  @dmccraw @knappe @coreycondardo Any additional thoughts on this before I put it out to a broader audience? Would love to get this established as its only about 50% of commits and PRs that are getting tagged with this currently

**Comment by coreycondardo** [comment]
@wbarn can you provide an example of: `Prefix commit messages and pull requests with appropriate JIRA or other ticket number.`?

Do you mean on every single commit we want to associate the ticket #? like:
```
MNG-1115 - Adds foo to the bar endpoint
MNG-1115 - Adds blah to the foo endpoint
MNG-1115 - Update changelog
```
as opposed to just making meaningful commits:
```
Adds foo to the bar endpoint
Adds blah to the foo endpoint
Update changelog
```

I think it's worth defining the purpose of adding this to the style guide:
* Commit provides insight into the reasoning for a change/addition/etc completed
* Increase signal to noise ratio (every commit tells a story, no commits are useless)
* Provide path back to larger issue (story, bug, etc)

Currently it seems like a mixed bag - either our branches indicate the issue, ie: `MNG-1115-do-foo-bar-thing` or have no context in the commit or the PR.

I wonder if a better, less error prone (and frankly easier to correct during PR) is to add the link inside the PR. That way we don't care where it is (jira, Github, zendesk PM software of the future) because a hard link will exist on the PR. Otherwise, MNG-1115 might be github, jira, future PM software, zendesk, etc. We 99% guarantee a PR is associated with a commit.

Just my $0.02.

**Comment by coreycondardo** [comment]
Just wanted to add... I'm not super opinionated on this, just throwing out ideas. As long as I can figure out _why_, it's usually enough. I want to balance practicality with information availability.

**Comment by semmons99** [comment]
I personally like the idea of a URL linking back to whatever issue spawned the commit. Who knows how long we will use JIRA, et cetera.

**Pull request merged**
