### PR TITLE
Update guide with RSpec  info

### PR DESCRIPTION
**Pull request by ryanwi**
This is a clean way to think about using context in RSpec

### CODE REVIEW

**Comment by chardoublestar** [comment]
I also like the guidance here for contexts. I wanted to see if we were okay with nesting contexts? Here is an example I'm working on:
```
RSpec.describe DivisionLogoResolver do
  context "when division does not have a custom logo" do
    context "when root division does not have a custom logo" do
      it "returns the TeamSnap logo"
    end

    context "when root division has a custom logo" do
      it "returns the root division logo"
    end
end
```

**Comment by glanotte** [comment]
@chardoublestar I know some might disagree with me, but I like nested contexts. When dealing with crazy scenarios (of which we have plenty), I feel it helps me think about it.

**Comment by coreycondardo** [comment]
seconded. I like to treat contexts as single purpose, and if two can happen at once, that to me warrants nesting. Saying "and" in a context to me is a problem, because you might have the same situation later, which a slight change.. that turns into "when you are tall and handsome and smart" which just gets insane.

**Comment by ryanwi** [comment]
I'm not a fan of nested contexts, the shallower the better. Deep nesting may call for smaller, shallower tests IMO.

**Comment by ryanwi** [comment]
I'm ok with the 2 level Charlie shows.

**Pull request merged**
