### PR TITLE
Multi line hash commas

### PR DESCRIPTION
**Pull request by chardoublestar**
re: multi-line hash w/ commas on every line:
at first i was like :grey_question: 
then i was like :+1:

### CODE REVIEW

**Comment by semmons99** [comment]
I like it. JavaScript hates it but Ruby, like the honeybadger don't care. What does everyone else think?

**Comment by knappe** [comment]
I'm seriously adverse to it.  But that is mainly because -Javascript- IE6 broke me.  https://jslinterrors.com/extra-comma

**Comment by chardoublestar** [comment]
Interesting, I thought it was already "accepted", but left out of the style guide by accident. Regardless, I'm all for making it official now that I've warmed up to it :stuck_out_tongue_winking_eye: But it seems like the kind of thing that requires more than a simple majority?

**Comment by semmons99** [comment]
we strive for consensus, or at least no hostile feelings towards new
policies

On Wed, Feb 17, 2016 at 11:03 PM chardoublestar <notifications@github.com>
wrote:

> Interesting, I thought it was already "accepted", but left out of the
> style guide by accident. Regardless, I'm all for making it official now
> that I've warmed up to it [image: :stuck_out_tongue_winking_eye:] But it
> seems like the kind of thing that requires more than a simple majority?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/teamsnap/guides/pull/21#issuecomment-185533747>.
>
-- 

*Shane Emmons* | CTO
TeamSnap - The easiest way to manage your team
(810) 834-9542 | shane@teamsnap.com | What is TeamSnap?

**Comment by glanotte** [comment]
I am adverse to not having it :trollface: kidding. I really like it, but if the team is adverse I can relent.

**Comment by knappe** [comment]
I'm fine with this.  Old wounds do heal. :)

**Comment by coreycondardo** [comment]
i like doing,
it but either way,
is cool,

**Comment by dmccraw** [comment]
I like the comma at the edn because of the one line diff issue! :ship: it!

**Comment by jjmocko** [comment]
The extra comma bothers me a bit, but I can get behind this. The extra line in the commits bothers me as well, so I might just need more coffee. :+1:

**Comment by PositiveControl** [comment]
Not a huge fan of it, from a style perspective, but I think @chardoublestar has a valid point: prevents 2-line diffs. So I conceded to the majority.  No strong feelings.

**Comment by kyleries** [comment]
I can just about guarantee I won't comply with this mostly on account of:

-  habit**,**
-  my mental model of lists**,**
-  and a third reason that is only here for comical illustration**,**

 :laughing: 

But, I'm ok with this change so long as it's accompanied by a Rubocop implementation that will correct this (and other nitpicks) automatically, streamlining code reviews and ensuring that all files can be brought into compliance at once. The style guide quickly becomes counterproductive when changes are made mid-stream that can't be applied to the full codebase. For example, a PR whose style is consistent with the rest of the file that is nitpicked into compliance with the style guide immediately introduces varying styles in the same file! An outcome that, to me, is the exact opposite of our goal here.

Finally, for what it's worth, the [ruby community has spoken on this](https://github.com/bbatsov/ruby-style-guide/pull/290) and it was deemed a "bad" thing to have trailing comma's on multi-line lists, though given the split nature of the debate, it was added as an option to Rubocop [an example of which can be seen here in this project's config](https://github.com/ad2games/rubocop-ci/pull/1)

**Comment by chardoublestar** [comment]
> The style guide quickly becomes counterproductive when changes are made mid-stream that can't be applied to the full codebase. For example, a PR whose style is consistent with the rest of the file that is nitpicked into compliance with the style guide immediately introduces varying styles in the same file!

This is really interesting. I think in the end, I disagree about the counterproductive-ness. I admit I have not yet had the experience of nitpicking portions of a file into compliance when the rest of the file is in an old/different style.

I don't know if the guide is meant more as something to strive for, or something to vehemently uphold, and I'm guessing the answer is nuanced, complicated, and changes depending on the season.

The fact that the varying style issue has happened before tells me that this guide is something to strive for and as the standards evolve, implementing them can be hard. I think that a Rubocop implementation (do any exist within TeamSnap yet?) addresses the implementation side of all these changes, and might be a separate, worthwhile task.

I'm curious if this is the straw breaking the camel's back? Did y'all discuss this back when APIv3, Ruby 2.3, or other things triggered new style changes?

**Comment by semmons99** [comment]
trailing comma is so ugly. The extra diff isn't much of a big deal IMO compared to all the legacy stuff we'd need to update and the habits of everyone we need to break. Does someone love this so much they want to fight for it? Otherwise I say *barf* and close this.

**Comment by semmons99** [comment]
barf

**Comment by glanotte** [comment]
I like the feature but it is pointless unless everyone will use it. It is also a bit more controversial than I would care for, so nuke away.

**Pull request closed without merging**
